create or replace PACKAGE ORAMARKER_LOG_PKG AS 

  c_debug CONSTANT INTEGER := 1;
  
  c_info CONSTANT INTEGER := 2;
  
  c_error CONSTANT INTEGER := 3;
  
  PROCEDURE INFO(p_msg VARCHAR2);
  PROCEDURE DEBUG(p_msg VARCHAR2);
  PROCEDURE ERROR(p_msg VARCHAR2);
END ORAMARKER_LOG_PKG;
/